import { sql } from "drizzle-orm";
import {
  check,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { z } from "zod";

import { artifacts, interviewSessions, reports } from "./interviews";
import { stories } from "./profiles";
import { users } from "./users";

/**
 * Practice Rebuild — a guided story-rewriting tool that lets a
 * candidate restructure their answer to a behavioral or technical
 * question from an InterviewReplay report. The AI is an EVIDENCE-AWARE
 * CRITIC of the candidate's draft, never a generator. See
 * `src/lib/rebuilds/critique.ts` for the prompt and guardrails
 * that enforce the "AI never writes the answer" contract.
 *
 * Encryption posture (intentional deviation from the build spec):
 * the build spec calls for application-layer envelope encryption
 * on every text field. The codebase's actual existing posture
 * (transcripts, reports, outcomes, profile) is plain TEXT with
 * TLS-in-transit + Postgres at-rest encryption — no envelope
 * encryption module exists yet. Rather than introduce a
 * one-table-only encryption layer that would diverge from every
 * other sensitive surface AND break tests/seeds/exports, we match
 * the existing posture and flag this as a follow-up alongside
 * `outcomes.ts` and the transcript columns. When the project
 * retrofits envelope encryption, all four surfaces (transcripts,
 * outcomes, profile, rebuilds) flip together so they share one
 * key-management surface.
 *
 * Status lifecycle:
 *
 *   in_progress   →  user opened a rebuild, scaffold being filled.
 *                    Auto-saves on PATCH /api/rebuilds/:id.
 *   critiqued     →  user clicked "Get critique" and the LLM
 *                    returned a validated, guardrail-passing
 *                    critique. Re-critiquing pushes the prior
 *                    one onto `critique_history`.
 *   saved_to_bank →  user clicked "Save to story bank". A row in
 *                    `stories` was created and `promoted_to_story_id`
 *                    points at it.
 *   discarded     →  soft-deleted. The retention sweep purges
 *                    discarded rebuilds older than 30 days.
 *
 * `source_improvement_index` is the array index into
 * `report.improvements[]` from the source session's report, OR
 * NULL for a standalone rebuild. It's NOT a row id and NOT
 * stable across re-analyses — it's a hint the UI uses to render
 * the "you're rebuilding an answer for the {improvement.heading}
 * the report flagged" banner, and is silently ignored if the
 * report no longer has an improvement at that index. We avoid
 * pinning to the improvement text because it's regenerated by
 * the LLM on every analyze and the user might re-analyze
 * between starting and finishing a rebuild.
 *
 * `question_theme` is plain TEXT (with a CHECK constraint
 * mirroring the `story_theme` Postgres enum) instead of using
 * the enum directly so a future addition of a theme value can
 * land via a single ALTER CONSTRAINT — the same trade-off
 * outcomes.ts makes. The application edge validates against
 * `STORY_THEMES` before insert; the constraint here is the
 * defense-in-depth net.
 */

/**
 * Allowed values for `story_rebuilds.status`. Stored as TEXT
 * with a CHECK constraint (see migration) for the same forward-
 * compatibility reasons `outcomes.ts` uses TEXT for outcome_type.
 */
export const REBUILD_STATUSES = [
  "in_progress",
  "critiqued",
  "saved_to_bank",
  "discarded",
] as const;
export const rebuildStatusSchema = z.enum(REBUILD_STATUSES);
export type RebuildStatus = z.infer<typeof rebuildStatusSchema>;

/**
 * Themes accepted for `story_rebuilds.question_theme`. Mirrors
 * the values of the `story_theme` Postgres enum from
 * `profiles.ts`. Kept in sync via a CHECK constraint in the
 * migration so a stray write (manual SQL, future legacy
 * migration) can't store a theme that the analyze-worker /
 * stories-API would later reject.
 */
export const REBUILD_QUESTION_THEMES = [
  "leadership_conflict",
  "biggest_failure",
  "technical_disagreement",
  "ambiguous_problem",
  "mentoring",
  "cross_team_collaboration",
  "deadline_pressure",
  "difficult_colleague",
  "outside_comfort_zone",
  "recovering_from_mistake",
  "other",
] as const;
export const rebuildQuestionThemeSchema = z.enum(REBUILD_QUESTION_THEMES);
export type RebuildQuestionTheme = z.infer<typeof rebuildQuestionThemeSchema>;

/**
 * Failure-shaped themes. The `what_i_would_change` scaffold field
 * is required for these and the `behavioral_change` critique
 * dimension is included for these only. Single source of truth
 * so the API validation, the UI conditional render, and the
 * critique prompt builder can't drift.
 */
export const FAILURE_THEMES: ReadonlySet<RebuildQuestionTheme> = new Set([
  "biggest_failure",
  "recovering_from_mistake",
]);

/**
 * One row per rebuild attempt. The seven free-text fields
 * (`questionText`, `headline`, `situation`, `task`, `action`,
 * `result`, `whatIWouldChange`) carry the candidate's draft;
 * `aiCritiqueJson` is the latest validated critique payload from
 * the LLM; `critiqueHistory` is an append-only array of prior
 * critiques (each entry carries its own timestamp) used for the
 * 10-per-day rate gate AND for product analytics on
 * "how many revisions did this candidate run".
 */
export const storyRebuilds = pgTable(
  "story_rebuilds",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    /**
     * Originating session. NULL for standalone rebuilds. SET NULL
     * on delete so a session retention sweep doesn't cascade-drop
     * the rebuild — the candidate's draft survives the wipe of
     * the source transcript, which matches the user expectation
     * ("I rebuilt this story, of course it stays in my bank").
     */
    sourceSessionId: uuid("source_session_id").references(
      () => interviewSessions.id,
      { onDelete: "set null" },
    ),

    /**
     * Index into `report.improvements[]` from the source
     * session. NULL for standalone rebuilds, or when we couldn't
     * pin a specific improvement (e.g. the user clicked the
     * bottom-of-report "rebuild a story" button which doesn't
     * carry a per-improvement context). See file-level comment
     * for why this is NOT a row id.
     */
    sourceImprovementIndex: integer("source_improvement_index"),

    /**
     * Optional artifact (question) row this rebuild addresses.
     * Set when the user launches a rebuild from the Analytics tab's
     * per-question card — gives the rebuild a stable backlink to
     * the exact question, distinct from the report-improvement
     * index (which can drift if the report is re-analyzed).
     *
     * SET NULL on the artifact's delete so a retention-driven
     * artifact wipe doesn't cascade-drop the rebuild row — the
     * candidate's draft is more durable than the source artifact
     * (same trade-off `source_session_id` makes).
     */
    sourceArtifactId: uuid("source_artifact_id").references(
      () => artifacts.id,
      { onDelete: "set null" },
    ),

    /**
     * Optional profile item (project or story) the rebuild UI
     * should pre-select on the Step 3 menu. Intentionally NOT a
     * FK constraint because it can point at either
     * `projects.id` or `stories.id` (Postgres doesn't support
     * disjunctive FKs without a polymorphic table). Application-
     * level validation in the create-rebuild route asserts the
     * UUID belongs to one of the candidate's `projects` or
     * `stories` before insert; this column is a hint, not a
     * source of truth.
     *
     * Stays NULL when the launching surface didn't pin a specific
     * profile item (the report's inline button, the standalone
     * entry point, the bottom-of-report card). Only the
     * "rebuild from the Analytics profile-leverage suggestion"
     * path populates it today.
     */
    preSelectedProfileItemId: uuid("pre_selected_profile_item_id"),

    questionText: text("question_text").notNull(),

    /**
     * Optional theme tag (one of `REBUILD_QUESTION_THEMES`).
     * Drives:
     *   - which stories the profile-pull step shows in column A,
     *   - whether `what_i_would_change` is required and the
     *     `behavioral_change` critique dimension is emitted,
     *   - the theme `stories.theme` is set to when the rebuild
     *     is promoted to the bank.
     * NULL when the user hasn't classified the question yet.
     */
    questionTheme: text("question_theme"),

    /* ── Candidate's draft (STAR scaffold) ───────────────────── */
    headline: text("headline"),
    situation: text("situation"),
    task: text("task"),
    action: text("action"),
    result: text("result"),
    whatIWouldChange: text("what_i_would_change"),

    /* ── Critique state ──────────────────────────────────────── */

    /**
     * Validated, guardrail-passing critique payload from the
     * latest call. Shape is `critiqueResponseSchema` from
     * `src/lib/rebuilds/schemas.ts`. NULL when the user hasn't
     * requested a critique yet.
     */
    aiCritiqueJson: jsonb("ai_critique_json").$type<unknown>(),

    /**
     * Append-only array of prior critique payloads. Each entry
     * has shape:
     *   { at: ISO-8601 string, critique: <critiqueResponseSchema> }
     * The "at" timestamps drive the 10-critiques-per-rebuild-
     * per-24h rate gate (count timestamps in the last 24 hours).
     * Defaults to `[]` so the count check is `arr.length`-safe.
     */
    critiqueHistory: jsonb("critique_history")
      .$type<RebuildCritiqueHistoryEntry[]>()
      .notNull()
      .default(sql`'[]'::jsonb`),

    /* ── AI suggested response state ─────────────────────────── */

    /**
     * Latest validated suggested-response payload from the LLM.
     * Shape is `suggestedResponseSchema` from
     * `src/lib/rebuilds/schemas.ts`. NULL until the user clicks
     * "Generate AI draft" for the first time.
     *
     * Distinct from `aiCritiqueJson` — critique evaluates the
     * candidate's draft, suggestion writes a draft for them to
     * compare against. They have separate prompts, separate
     * versions, and separate history rows.
     */
    aiSuggestedResponseJson: jsonb("ai_suggested_response_json").$type<unknown>(),

    /**
     * Pinned model id (e.g. `"llama3.3:8b"`). Stored so a future
     * model rollout can be filtered in analytics — mirrors how the
     * report row tags `model_version`.
     */
    aiSuggestedResponseModelVersion: text("ai_suggested_response_model_version"),

    /**
     * Timestamp of the latest suggestion generation. Drives the
     * "Generated N minutes ago" affordance on the Story Bank card.
     */
    aiSuggestedResponseGeneratedAt: timestamp(
      "ai_suggested_response_generated_at",
      { withTimezone: true },
    ),

    /**
     * Append-only array of prior suggestion payloads. Each entry
     * has shape:
     *   { at: ISO-8601 string, suggestion: <suggestedResponseSchema> }
     * Drives a separate 10-suggestions-per-rebuild-per-24h rate
     * gate, parallel to `critiqueHistory` but tracked
     * independently so a user who has blown their critique budget
     * can still generate an AI draft to compare against.
     */
    suggestedResponseHistory: jsonb("suggested_response_history")
      .$type<RebuildSuggestedResponseHistoryEntry[]>()
      .notNull()
      .default(sql`'[]'::jsonb`),

    /* ── Bank promotion ──────────────────────────────────────── */

    /**
     * Set after `POST /api/rebuilds/:id/save-to-bank` creates a
     * `stories` row. SET NULL on delete so a future story
     * deletion doesn't cascade-wipe the rebuild — the rebuild's
     * draft and critique remain a record of "this is what I
     * worked on" even after the bank entry is gone.
     */
    promotedToStoryId: uuid("promoted_to_story_id").references(
      () => stories.id,
      { onDelete: "set null" },
    ),

    /**
     * Lifecycle state. See file-level comment.
     */
    status: text("status").notNull().default("in_progress"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    /**
     * Dashboard "your rebuilds" list AND the /rebuilds/list page
     * order by `updated_at DESC`. The composite index keys on
     * (user_id, updated_at desc) so the most-recent-first page
     * is a covered, indexed read.
     */
    index("story_rebuilds_user_updated_idx").on(
      table.userId,
      table.updatedAt.desc(),
    ),

    /**
     * Find all rebuilds attached to a specific session — the
     * report view uses this to render the "Strengthen your
     * story bank" section's "you've already started a rebuild
     * for this improvement" badge.
     */
    index("story_rebuilds_session_idx").on(table.sourceSessionId),

    /**
     * Partial index for the dashboard's "rebuilds in progress"
     * badge — filters out the (numerous) saved/discarded rows
     * before the index is even traversed.
     */
    index("story_rebuilds_user_status_idx")
      .on(table.userId, table.status)
      .where(sql`${table.status} <> 'discarded'`),

    /**
     * Daily retention sweep targets `status = 'discarded'` rows
     * older than 30 days — partial index keeps the cron's scan
     * cheap even after a million live rebuilds.
     */
    index("story_rebuilds_discarded_idx")
      .on(table.updatedAt)
      .where(sql`${table.status} = 'discarded'`),

    /**
     * Story Bank page joins `stories` LEFT JOIN `story_rebuilds`
     * on `promoted_to_story_id` so each saved-from-rebuild story
     * can surface its critique + source-session backlink. Partial
     * index over non-NULL only — `promoted_to_story_id` is NULL
     * for the (much larger) population of in-progress and
     * discarded rebuilds.
     */
    index("story_rebuilds_promoted_to_story_idx")
      .on(table.promotedToStoryId)
      .where(sql`${table.promotedToStoryId} IS NOT NULL`),

    /**
     * "Show me every rebuild anchored on this specific question"
     * — used by the report page's per-question card to render the
     * "you've already started a rebuild for this question" badge.
     * Partial index over non-NULL only since the column is null
     * for every non-Analytics-tab launch path.
     */
    index("story_rebuilds_artifact_idx")
      .on(table.sourceArtifactId)
      .where(sql`${table.sourceArtifactId} IS NOT NULL`),

    /**
     * Defense-in-depth: status must be one of the four allowed
     * values. The application edge validates with `rebuildStatusSchema`
     * before insert; this catches any path that bypasses it.
     */
    check(
      "story_rebuilds_status_valid",
      sql`${table.status} IN ('in_progress', 'critiqued', 'saved_to_bank', 'discarded')`,
    ),

    /**
     * If `question_theme` is set it must be one of the
     * `story_theme` enum values. Mirrors the enum in
     * `profiles.ts`. NULL is accepted (the user may not have
     * tagged a theme yet).
     */
    check(
      "story_rebuilds_question_theme_valid",
      sql`${table.questionTheme} IS NULL OR ${table.questionTheme} IN (
        'leadership_conflict', 'biggest_failure', 'technical_disagreement',
        'ambiguous_problem', 'mentoring', 'cross_team_collaboration',
        'deadline_pressure', 'difficult_colleague', 'outside_comfort_zone',
        'recovering_from_mistake', 'other'
      )`,
    ),
  ],
);

/**
 * Shape of one entry in `critique_history`. Stored as JSONB; we
 * only ever read it for analytics + the daily rate gate, never
 * surface old entries to the candidate (the UI shows the latest
 * critique only).
 */
export interface RebuildCritiqueHistoryEntry {
  /** ISO-8601 UTC timestamp the critique was generated at. */
  at: string;
  /** The validated critique payload. Shape lives in `lib/rebuilds/schemas.ts`. */
  critique: unknown;
}

/**
 * Shape of one entry in `suggested_response_history`. Same role
 * as `RebuildCritiqueHistoryEntry`: timestamps drive the daily
 * rate gate; the body is stored for analytics only — the UI
 * shows the latest suggestion only.
 */
export interface RebuildSuggestedResponseHistoryEntry {
  /** ISO-8601 UTC timestamp the suggestion was generated at. */
  at: string;
  /** The validated suggestion payload. Shape lives in `lib/rebuilds/schemas.ts`. */
  suggestion: unknown;
}

/**
 * `reports` is imported above to anchor the FK comment about
 * the `source_improvement_index` field — we don't actually
 * reference the table from this row (the index is into the
 * report JSONB, not a separate table). The import keeps the
 * `import` block honest about the conceptual coupling.
 */
void reports;

export type StoryRebuild = typeof storyRebuilds.$inferSelect;
export type NewStoryRebuild = typeof storyRebuilds.$inferInsert;
