import { defineConfig, devices } from "@playwright/test";

/**
 * Playwright config for end-to-end smoke tests.
 *
 * Scope on purpose: this is the "is the app reachable, do the most
 * important pages render, does middleware actually gate /dashboard"
 * tier. Auth flow correctness lives in the Vitest suite — that's
 * faster, deterministic, and doesn't need a browser.
 *
 * The dev server is started by Playwright (and torn down at the end)
 * so contributors can `pnpm test:e2e` without juggling two terminals.
 */
const PORT = process.env.PORT ? Number(process.env.PORT) : 3100;
const BASE_URL = `http://localhost:${PORT}`;

export default defineConfig({
  testDir: "./tests/e2e",
  // Vitest specs use `.test.ts`; restrict Playwright to `.spec.ts` so
  // the two frameworks never accidentally pick up each other's files.
  testMatch: /.*\.spec\.ts/,
  // Run the local dev seed once before the suite starts. The
  // authenticated dashboard test relies on the seeded user + sample
  // sessions; the marketing and auth-gate specs don't, but the seed
  // is idempotent so paying for it once is harmless.
  globalSetup: "./tests/e2e/global-setup.ts",
  timeout: 30_000,
  expect: { timeout: 5_000 },
  fullyParallel: false,
  retries: process.env.CI ? 2 : 0,
  reporter: process.env.CI ? "github" : "list",

  use: {
    baseURL: BASE_URL,
    trace: "on-first-retry",
    actionTimeout: 5_000,
    // Pre-seed `ir-analytics-consent=declined` in localStorage so
    // the cookie consent banner doesn't render. Without this it sits
    // on top of the page (fixed-position, z-40) and intercepts the
    // first click of every test. The file is generated by
    // `tests/e2e/global-setup.ts` on every run so it tracks BASE_URL
    // even when PORT is overridden.
    storageState: "./tests/e2e/.storage-state.json",
  },

  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],

  webServer: {
    // Use a non-default port so a contributor's local dev server on
    // 3000 doesn't collide with the e2e instance.
    command: `next dev --turbopack --port ${PORT}`,
    url: BASE_URL,
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
    stdout: "pipe",
    stderr: "pipe",
    env: {
      // .env.local pins NEXTAUTH_URL=http://localhost:3000 for the
      // contributor's normal `pnpm dev` workflow. Auth.js v5 uses that
      // value for post-signin redirects, which breaks the e2e suite
      // running on PORT (default 3100). Override here so signin
      // redirects match the test server's actual port.
      NEXTAUTH_URL: BASE_URL,
    },
  },
});
