import "server-only";

export {
  generateReport,
  generateAnalytics,
  generateStoryHighlights,
  buildPlaceholderReport,
  buildFallbackReport,
  clampWithHeadAndTail,
  clampArtifactBlocks,
  sanitizeReportInput,
  parseJsonWithRepair,
  isThinTranscript,
  getLlmClient,
  LLM_MODEL_LARGE,
  LLM_MODEL_SMALL,
  MAX_TOKENS_BY_ROUND,
  CORE_MAX_TOKENS_BY_ROUND,
  ANALYTICS_MAX_TOKENS_BY_ROUND,
  STORIES_MAX_TOKENS_BY_ROUND,
  MAX_PROMPT_BODY_CHARS,
  MAX_TRANSCRIPT_BODY_CHARS,
  MAX_ARTIFACT_BODY_CHARS,
  THIN_TRANSCRIPT_MIN_WORDS,
  THIN_TRANSCRIPT_MIN_SECONDS,
  FALLBACK_MODEL_VERSION_PREFIX,
  LlmNotConfiguredError,
  LlmValidationError,
  type AnalyzeArgs,
  type AnalyzeResult,
  type AnalyticsResult,
  type StoryHighlightsResult,
  type FallbackReason,
  type JsonParseOk,
  type JsonParseErr,
} from "./client";
export {
  reportSchema,
  analyticsOutputSchema,
  storyHighlightsOutputSchema,
  strengthSchema,
  improvementSchema,
  communicationSignalsSchema,
  roundSpecificSchema,
  aiReadSchema,
  questionCoveredSchema,
  perQuestionAnalyticsSchema,
  profileLeverageSchema,
  starSignalsSchema,
  storyHighlightCategorySchema,
  storyHighlightSchema,
  type Report,
  type AnalyticsOutput,
  type StoryHighlightsOutput,
  type Strength,
  type Improvement,
  type CommunicationSignals,
  type RoundSpecific,
  type QuestionCovered,
  type PerQuestionAnalytics,
  type ProfileLeverage,
  type StarSignal,
  type StarSignals,
  type StoryHighlight,
  type StoryHighlightCategory,
} from "./schema";
export {
  findForbiddenLanguage,
  containsForbiddenLanguage,
  type ForbiddenLanguageHit,
} from "./forbidden";
export { rubricFor, RUBRIC_VERSION } from "./rubrics";
export { SYSTEM_PROMPT, SYSTEM_PROMPT_VERSION } from "./prompt";
export {
  isRebuildEligible,
  countRebuildEligible,
  orientationNoteCopy,
} from "./rebuild-eligibility";
export {
  HAIKU_MODEL,
  MAX_INFERENCE_TRANSCRIPT_CHARS,
  inferQuestions,
  parseAndValidate as parseInferenceResponse,
  runInferencePass,
  type InferenceItem,
  type InferQuestionsArgs,
} from "./infer-questions";
