/**
 * Shared, pure helpers consumed by the Analytics-tab chart and
 * card components. Kept in their own module because:
 *
 *   1. Each chart component imports a subset of these — extracting
 *      them avoids circular imports between sibling components.
 *   2. They unit-test cleanly without a DOM (vitest's plain
 *      `*.test.ts` files can exercise them without jsdom).
 *
 * No React imports here. Anything that returns JSX lives in the
 * component file it belongs to.
 */

import type {
  PerQuestionAnalytics,
  ProfileLeverage,
  QuestionCovered,
  StarSignal,
} from "@/lib/llm";

import type { LengthBand } from "@/lib/analytics/per-session";

/* ────────────────────────────────────────────────────────────── */
/* Analytics-feature launch cutoff                                */
/* ────────────────────────────────────────────────────────────── */

/**
 * Hard cut-off used to decide whether a report SHOULD have been
 * generated with the current per-question-analytics prompt
 * section. The value mirrors the latest prompt bump in
 * `src/lib/llm/prompt.ts` (`SYSTEM_PROMPT_VERSION`) — every report
 * created at or after this instant ran against the current prompt
 * and, if `per_question_analytics` is still absent, the LLM
 * omitted it deliberately (genuinely empty / failed transcript,
 * `questionsCovered: []`).
 *
 * The cutoff was bumped to 2026-05-18 alongside the prompt
 * revision that started driving entries off `questionsCovered`
 * (the previous 2026-05-17 version required an artifact-backed
 * UUID per entry and therefore produced no analytics for sessions
 * whose questions were all transcript-inferred — see the prompt
 * comment header for the full history). Bumping the cutoff makes
 * reports written between 2026-05-17 and 2026-05-18 fall into the
 * "legacy" branch again so re-analyzing them under the new prompt
 * actually populates the charts.
 *
 * Used by the Analytics tab's `LegacyReportPlaceholder` to swap
 * the copy + CTA: pre-cutoff reports show the "click re-analyze"
 * message (re-analysis with the new prompt will fix them); post-
 * cutoff reports show a "we couldn't compute analytics" message
 * and DO NOT offer the re-analyze button (it wouldn't change
 * anything and would re-charge the user or burn their free 24h
 * slot for nothing).
 *
 * Exported so the runbook query, the unit tests, and the
 * placeholder all stay anchored on the same instant.
 */
export const ANALYTICS_FEATURE_LAUNCHED_AT = new Date(
  "2026-06-01T00:00:00.000Z",
);

/**
 * True when the report's `created_at` is at or after the analytics-
 * feature launch instant, i.e. the report was generated by the
 * current prompt and its absence of `per_question_analytics` is
 * informative ("the LLM ran the new section and chose not to emit
 * anything"), not legacy ("the prompt section didn't exist yet").
 *
 * Returns `false` when `reportCreatedAt` is `null` / `undefined`
 * so harness / Storybook renders fall through to the original
 * legacy-message branch — the pre-existing behavior when no date
 * is available.
 *
 * Pure / boundary-only: extracted from the React component file so
 * vitest can pin the cutoff semantics without spinning up a DOM
 * renderer (the project doesn't ship one — see the comment header
 * on `analytics-utils.test.ts`).
 */
export function isPostLaunchReport(
  reportCreatedAt: Date | null | undefined,
): boolean {
  if (reportCreatedAt == null) return false;
  return reportCreatedAt.getTime() >= ANALYTICS_FEATURE_LAUNCHED_AT.getTime();
}

/* ────────────────────────────────────────────────────────────── */
/* Time formatting                                                */
/* ────────────────────────────────────────────────────────────── */

/**
 * Format a duration in seconds as `M:SS`. Used by the per-question
 * card duration label and by the time-distribution bar's segment
 * title attributes.
 *
 * Floors the seconds and clamps the input non-negative so a
 * malformed `-1` doesn't render as `-1:0-1`. Matches the format
 * used by `formatMmSs` in `lib/analytics/narratives.ts` — kept as
 * a sibling rather than imported to keep this module free of
 * server-only transitive imports.
 */
export function formatMmSs(seconds: number): string {
  const safe = Math.max(0, Math.floor(seconds));
  const m = Math.floor(safe / 60);
  const s = safe % 60;
  return `${m}:${s.toString().padStart(2, "0")}`;
}

/* ────────────────────────────────────────────────────────────── */
/* STAR completeness summary line                                 */
/* ────────────────────────────────────────────────────────────── */

/**
 * Render the right-aligned summary line above each STAR bar
 * (e.g. "92% present, 8% weak"). Includes only non-zero segments
 * so a fully-present dimension reads "100% present" instead of
 * "100% present, 0% weak, 0% missing".
 *
 * Returns the empty string when the dimension has zero
 * contributors — the renderer can use that to skip the right
 * column entirely.
 */
export function formatStarSummary(totals: {
  present: number;
  weak: number;
  missing: number;
  total: number;
}): string {
  if (totals.total === 0) return "";
  const pct = (n: number): number => Math.round((n / totals.total) * 100);
  const parts: string[] = [];
  const presentPct = pct(totals.present);
  const weakPct = pct(totals.weak);
  const missingPct = pct(totals.missing);
  if (presentPct > 0) parts.push(`${presentPct}% present`);
  if (weakPct > 0) parts.push(`${weakPct}% weak`);
  if (missingPct > 0) parts.push(`${missingPct}% missing`);
  return parts.join(", ");
}

/* ────────────────────────────────────────────────────────────── */
/* STAR badge style + label                                       */
/* ────────────────────────────────────────────────────────────── */

export type StarDimensionKey = "situation" | "task" | "action" | "result";

const STAR_LETTERS: Record<StarDimensionKey, string> = {
  situation: "S",
  task: "T",
  action: "A",
  result: "R",
};

const STAR_LABELS: Record<StarDimensionKey, string> = {
  situation: "Situation",
  task: "Task",
  action: "Action",
  result: "Result",
};

/**
 * Return the single-letter abbreviation used on the per-question
 * card's badges. Kept as a function (not a constant lookup) so the
 * call sites read the same way the four-dimension iteration does.
 */
export function starLetterFor(dim: StarDimensionKey): string {
  return STAR_LETTERS[dim];
}

export function starLabelFor(dim: StarDimensionKey): string {
  return STAR_LABELS[dim];
}

/**
 * Shape for the per-dimension badge on a `MergedQuestionRow`. Drives
 * the badge's background color, text color, and trailing glyph.
 *
 * Tests pin the glyph + class shape so a copy-edit on the card
 * doesn't accidentally drop the visual delta between present /
 * weak / missing.
 */
export interface StarBadgeStyle {
  /** Glyph trailing the letter — ✓ / ⚠ / ✗. */
  glyph: string;
  /** Inline-style background color reference. */
  background: string;
  /** Inline-style text color reference. */
  color: string;
}

const STAR_BADGE_PRESENT: StarBadgeStyle = {
  glyph: "✓",
  background: "var(--color-success-bg)",
  color: "var(--color-success-text)",
};
const STAR_BADGE_WEAK: StarBadgeStyle = {
  glyph: "⚠",
  background: "var(--color-warning-bg)",
  color: "var(--color-warning-text)",
};
const STAR_BADGE_MISSING: StarBadgeStyle = {
  glyph: "✗",
  background: "var(--color-danger-bg)",
  color: "var(--color-danger-text)",
};

/**
 * Map a STAR signal value to its rendered-badge style. Returns
 * `null` for `'na'` so the caller can choose to omit the badge
 * (we render the `N/A` aggregate badge separately when ALL four
 * are 'na' — see `isAllNa`).
 */
export function starBadgeStyleFor(value: StarSignal): StarBadgeStyle | null {
  switch (value) {
    case "present":
      return STAR_BADGE_PRESENT;
    case "weak":
      return STAR_BADGE_WEAK;
    case "missing":
      return STAR_BADGE_MISSING;
    case "na":
      return null;
  }
}

/**
 * True when every STAR dimension on this entry is `'na'` — the
 * card renders a single "N/A" badge in that case rather than four
 * individual badges (none of which would convey signal).
 */
export function isAllNa(item: PerQuestionAnalytics): boolean {
  const s = item.star_signals;
  return (
    s.situation === "na" &&
    s.task === "na" &&
    s.action === "na" &&
    s.result === "na"
  );
}

/**
 * True when at least one STAR dimension is 'weak' or 'missing' on
 * a scoreable entry. Drives the "Rebuild this answer" affordance
 * on per-question cards.
 */
export function hasWeakOrMissingStar(item: PerQuestionAnalytics): boolean {
  if (isAllNa(item)) return false;
  const s = item.star_signals;
  return (
    s.situation === "weak" ||
    s.situation === "missing" ||
    s.task === "weak" ||
    s.task === "missing" ||
    s.action === "weak" ||
    s.action === "missing" ||
    s.result === "weak" ||
    s.result === "missing"
  );
}

/* ────────────────────────────────────────────────────────────── */
/* Answer-length target-band geometry                              */
/* ────────────────────────────────────────────────────────────── */

/**
 * Compute the 90s–180s target band's vertical geometry for the
 * answer-length distribution chart.
 *
 * The band is rendered as a HORIZONTAL stripe across the full
 * chart width — its bottom edge sits at the y-position
 * corresponding to 90s and its top edge at 180s, both expressed
 * as percentages of the chart's vertical scale (0 → maxDuration).
 * The percentage values match the CSS positioning we use:
 *
 *   bottom: `${bottomPct}%`   // distance from chart floor to 90s
 *   height: `${heightPct}%`   // span between 90s and 180s
 *
 * Clamping rules — both intentional, both keep the band visible
 * even when the data is degenerate:
 *
 *   1. `maxDuration <= 0` (defensive — the analyze pipeline
 *      guarantees positive durations) → use 1 so the math is
 *      finite and the caller still renders SOMETHING the user
 *      can read.
 *   2. `maxDuration < 180` → the 180s edge would otherwise sit
 *      above the chart top. We clamp the top edge to 100% so the
 *      band reads as "every bar of this short interview is in or
 *      below target", visually pinned at the chart top rather
 *      than scrolling off-screen.
 *   3. `maxDuration < 90` (rare; only happens when EVERY answer
 *      was under 90s) → bottom AND top both clamp to 100%; the
 *      band collapses to a single zero-height line at the chart
 *      top. The renderer can skip drawing the band in that case
 *      since `heightPct === 0`.
 *
 * Pure: no DOM / style imports. The pixel-space conversion lives
 * in the renderer (it knows how much of the chart height is
 * reserved for the bottom label rail).
 */
export interface AnswerLengthBandGeometry {
  /** Distance from chart floor to the 90s line, as % of chart height. */
  bottomPct: number;
  /** Distance from chart floor to the 180s line, as % of chart height. */
  topPct: number;
  /** Span between 90s and 180s, as % of chart height. May be 0. */
  heightPct: number;
}

export const ANSWER_LENGTH_LOWER_TARGET_S = 90;
export const ANSWER_LENGTH_UPPER_TARGET_S = 180;

export function computeAnswerLengthBandGeometry(
  maxDurationSeconds: number,
): AnswerLengthBandGeometry {
  const safeMax = maxDurationSeconds > 0 ? maxDurationSeconds : 1;
  const bottomPct = Math.min(
    100,
    (ANSWER_LENGTH_LOWER_TARGET_S / safeMax) * 100,
  );
  const topPct = Math.min(
    100,
    (ANSWER_LENGTH_UPPER_TARGET_S / safeMax) * 100,
  );
  const heightPct = Math.max(0, topPct - bottomPct);
  return { bottomPct, topPct, heightPct };
}

/* ────────────────────────────────────────────────────────────── */
/* Time-distribution rendering-mode switch                         */
/* ────────────────────────────────────────────────────────────── */

/**
 * Threshold at which the per-question time-distribution surface
 * flips from the stacked-segment bar to the row list. Spec:
 *
 *   - ≤ THRESHOLD questions → stacked bar (compact, comparative).
 *   - >  THRESHOLD questions → row list (segments would be too
 *                              thin to label / hover reliably).
 *
 * Exported so the unit tests and the renderer share the same
 * cutoff without a magic number sprinkled in two places.
 */
export const TIME_DISTRIBUTION_ROW_LIST_THRESHOLD = 10;

export type TimeDistributionRenderMode = "stacked_bar" | "row_list";

export function pickTimeDistributionRenderMode(
  itemCount: number,
): TimeDistributionRenderMode {
  return itemCount > TIME_DISTRIBUTION_ROW_LIST_THRESHOLD
    ? "row_list"
    : "stacked_bar";
}

/* ────────────────────────────────────────────────────────────── */
/* AI Read TL;DR excerpt                                    */
/* ────────────────────────────────────────────────────────────── */

/**
 * Max characters in the top-of-report AI Read TL;DR
 * excerpt. The full paragraph is capped at 1500 chars by the
 * report schema; this short version is intentionally tight so the
 * teaser fits next to the readiness score without pushing the
 * tabs below the fold.
 */
export const AI_READ_TLDR_MAX_CHARS = 250;

/**
 * Build the truncated teaser for the top-of-report AI Read
 * summary. Truncates at a word boundary when possible (so we
 * don't slice mid-word) and appends an ellipsis when truncation
 * happened.
 *
 * Returns the original paragraph unchanged when it's already
 * within the cap. Empty / whitespace input is normalised to "" so
 * the renderer can skip the block entirely.
 */
export function buildInterviewReplayReadTldr(
  paragraph: string,
  maxChars: number = AI_READ_TLDR_MAX_CHARS,
): string {
  const trimmed = paragraph.trim();
  if (trimmed.length === 0) return "";
  if (trimmed.length <= maxChars) return trimmed;
  const slice = trimmed.slice(0, maxChars);
  const lastSpace = slice.lastIndexOf(" ");
  // Only honour the word boundary if it leaves at least 80% of the
  // budget — a single very long word at the start shouldn't get
  // truncated to a 5-character teaser.
  const cut =
    lastSpace > Math.floor(maxChars * 0.8) ? slice.slice(0, lastSpace) : slice;
  return `${cut.trimEnd()}…`;
}

/* ────────────────────────────────────────────────────────────── */
/* Confidence dot (collapsed per-question row)                    */
/* ────────────────────────────────────────────────────────────── */

/**
 * Tiny 8px coloured dot rendered on the LEFT of every collapsed
 * per-question row in place of the (deleted) confidence pill.
 *
 * Colour mapping follows the same semantic tokens the larger
 * pill used so a candidate already familiar with the previous
 * grammar reads the new dot the same way:
 *
 *   high   → success (green/teal)
 *   medium → warning (amber)
 *   low    → danger  (coral)
 *   null   → neutral grey (the row is paired with a coverage
 *            entry whose confidence we couldn't resolve, or the
 *            row is analytics-only on a legacy report)
 *
 * Returns CSS-variable references — the same tokens the STAR
 * badges use — so the colour stays in lockstep with the theme.
 */
export function confidenceDotColor(
  confidence: "high" | "medium" | "low" | null | undefined,
): string {
  switch (confidence) {
    case "high":
      return "var(--color-success)";
    case "medium":
      return "var(--color-warning)";
    case "low":
      return "var(--color-danger)";
    default:
      return "var(--color-text-tertiary)";
  }
}

/**
 * Accessible label / hover tooltip for the confidence dot.
 * Mirrors the (deleted) pill copy so screen-reader users get the
 * same wording across the previous and new surfaces.
 */
export function confidenceDotLabel(
  confidence: "high" | "medium" | "low" | null | undefined,
): string {
  switch (confidence) {
    case "high":
      return "High confidence";
    case "medium":
      return "Medium confidence";
    case "low":
      return "Low confidence";
    default:
      return "Confidence unknown";
  }
}

/* ────────────────────────────────────────────────────────────── */
/* Length-band colors                                             */
/* ────────────────────────────────────────────────────────────── */

/**
 * Pick the bar color for the answer-length distribution chart. The
 * three colors map onto the same semantic tokens the STAR badges
 * use (success / warning / danger), so a candidate eyeballing the
 * report reads "green = good" consistently across surfaces.
 */
export function lengthBandColor(band: LengthBand): string {
  switch (band) {
    case "in_range":
      return "var(--color-success)";
    case "short":
      return "var(--color-warning)";
    case "long":
      return "var(--color-danger)";
    // Closing / clarification questions aren't graded against the
    // 90–180s target — paint them neutral so the eye doesn't
    // mistake a quick "Any questions for me?" for a length problem.
    case "meta":
      return "var(--color-text-tertiary)";
  }
}

/* ────────────────────────────────────────────────────────────── */
/* Time-distribution alternation                                  */
/* ────────────────────────────────────────────────────────────── */

/**
 * Alternating purple shades used by the time-distribution stacked
 * bar. The two values are purely visual separation — they carry no
 * semantic meaning and intentionally don't use the success / warn /
 * danger tokens (which would imply a verdict on individual
 * questions). The pair matches `--color-chart-4` and its light-
 * mode sibling pin in the spec.
 *
 * Kept as fixed hex values rather than CSS-variable references so
 * the alternation is the same across both themes — in dark mode
 * the chart-4 token shifts to a lighter purple but the contrast
 * step we need stays at this 7F77DD / AFA9EC pair.
 */
export const TIME_DISTRIBUTION_SHADE_EVEN = "#7F77DD";
export const TIME_DISTRIBUTION_SHADE_ODD = "#AFA9EC";

export function timeDistributionShadeAt(index: number): string {
  return index % 2 === 0
    ? TIME_DISTRIBUTION_SHADE_EVEN
    : TIME_DISTRIBUTION_SHADE_ODD;
}

/* ────────────────────────────────────────────────────────────── */
/* Profile leverage indicator                                     */
/* ────────────────────────────────────────────────────────────── */

/**
 * Resolved view of `profile_leverage` ready for the per-question
 * card to render. We do the noun-and-color decision here so the
 * card component stays focused on layout.
 *
 * `clickable: true` for `available_unused` only — that's the
 * status the spec wires to a Practice Rebuild launch with the
 * suggested item pre-selected. The other statuses are read-only
 * informational rows.
 */
export interface ProfileLeverageIndicator {
  text: string;
  color: string;
  clickable: boolean;
  suggestedItemId?: string;
}

export function formatProfileLeverage(
  leverage: ProfileLeverage,
): ProfileLeverageIndicator | null {
  switch (leverage.status) {
    case "used": {
      // We render even without a label so the candidate sees their
      // profile was used; the schema allows `referenced_item_label`
      // to be absent in pathological cases (older reports).
      const label = leverage.referenced_item_label ?? "a profile item";
      return {
        text: `Used ${label}`,
        color: "var(--color-success)",
        clickable: false,
      };
    }
    case "available_unused": {
      // The schema doesn't carry `suggested_item_type` directly —
      // we infer the noun from `referenced_item_type` when set
      // (the model sometimes emits both fields together) and
      // otherwise fall back to "story", which is the more common
      // surface in the rebuild flow.
      const noun =
        leverage.referenced_item_type === "project" ? "project" : "story";
      const label = leverage.suggested_item_label ?? "a stronger option";
      return {
        text: `Stronger ${noun} available: ${label}`,
        color: "var(--color-danger)",
        clickable: leverage.suggested_item_id !== undefined,
        suggestedItemId: leverage.suggested_item_id,
      };
    }
    case "no_match":
      return {
        text: "No matching profile content",
        color: "var(--color-text-tertiary)",
        clickable: false,
      };
  }
}

/* ────────────────────────────────────────────────────────────── */
/* Speech pace gauge math                                         */
/* ────────────────────────────────────────────────────────────── */

/**
 * Upper bound on the gauge's visible needle position. WPM values
 * above this still render their actual number in the centre text
 * — only the needle parks at the arc's right edge. Picked so the
 * three coloured bands (≤120 measured, 120-170 conversational,
 * 170-220 brisk) fit symmetrically across the 180° arc.
 */
export const SPEECH_PACE_GAUGE_MAX_VISIBLE_WPM = 220;

/**
 * Compute the gauge's three visible quantities from raw inputs.
 *
 * Returns `null` when there's no signal (zero duration OR zero
 * words). The component uses that null-return as its "don't
 * render" gate so the section above stays clean.
 *
 * `wpm` is the candidate-visible number rendered in the centre of
 * the gauge — derived without clamping so a 240 WPM round still
 * shows "240" even though the needle parks at 220.
 *
 * `visibleWpm` drives the needle position only. Clamped to
 * `[0, SPEECH_PACE_GAUGE_MAX_VISIBLE_WPM]`.
 *
 * `angleDegrees` maps `visibleWpm` to the rotation that takes the
 * needle from the left edge (-90°) to the right edge (+90°) over
 * the gauge's 180° arc. Linearly interpolated — the band
 * boundaries are visual (coloured stroke segments), not encoded
 * into the angle.
 */
export interface SpeechPaceGaugeMetrics {
  wpm: number;
  visibleWpm: number;
  angleDegrees: number;
}

/**
 * Physiological ceiling for human speech in WPM. The fastest
 * recorded auctioneers and speed-talkers peak around 400-450 WPM.
 * Anything above 500 is a data-quality problem (corrupted
 * durationSeconds, truncated audio, etc.) — we suppress the gauge
 * rather than show a meaningless five-digit number.
 */
export const SPEECH_PACE_MAX_PLAUSIBLE_WPM = 500;

export function computeSpeechPaceGaugeMetrics(
  wordCount: number,
  durationSeconds: number,
): SpeechPaceGaugeMetrics | null {
  if (wordCount <= 0 || durationSeconds <= 0) return null;
  const wpm = Math.round(wordCount / (durationSeconds / 60));
  // Guard against corrupted duration data (e.g. the transcription service returning
  // metadata.duration=15 for a 30-minute recording). Show nothing
  // rather than a physically impossible five-digit WPM.
  if (wpm > SPEECH_PACE_MAX_PLAUSIBLE_WPM) return null;
  const visibleWpm = Math.min(
    SPEECH_PACE_GAUGE_MAX_VISIBLE_WPM,
    Math.max(0, wpm),
  );
  const angleDegrees =
    -90 + (visibleWpm / SPEECH_PACE_GAUGE_MAX_VISIBLE_WPM) * 180;
  return { wpm, visibleWpm, angleDegrees };
}

/* ────────────────────────────────────────────────────────────── */
/* Coverage ↔ analytics matching                                  */
/* ────────────────────────────────────────────────────────────── */

/**
 * Normalise a question string for cross-array matching. The model
 * occasionally emits trivial whitespace / casing differences
 * between the `questionsCovered[i].question` string and the paired
 * `per_question_analytics[i].question_text` string (the latter is
 * "duplicated from the artifact for convenience" — see the schema
 * JSDoc — but the model is generative, not a memcpy). Collapsing
 * to a normalised key keeps the match robust without paying the
 * cost of a fuzzy-string library.
 */
function normaliseQuestionKey(text: string): string {
  return text.trim().toLowerCase().replace(/\s+/g, " ");
}

/**
 * Build a lookup table from normalised question text →
 * `QuestionCovered`. Returns `null` when the input is empty so the
 * caller can skip the per-card render path entirely.
 *
 * On a duplicate key (very rare — the model would have to emit two
 * questions that normalise to the same string), the FIRST entry
 * wins. The Analytics tab needs a single coverage record per
 * question and the order matches the report; preferring the first
 * keeps the rendered confidence stable across re-renders.
 */
export function buildCoverageLookup(
  coverage: ReadonlyArray<QuestionCovered> | undefined,
): ReadonlyMap<string, QuestionCovered> | null {
  if (!coverage || coverage.length === 0) return null;
  const map = new Map<string, QuestionCovered>();
  for (const q of coverage) {
    const key = normaliseQuestionKey(q.question);
    if (!map.has(key)) map.set(key, q);
  }
  return map;
}

/**
 * Resolve the `QuestionCovered` row that pairs with a given
 * per-question analytics entry. Lookup is by normalised question
 * text (see `buildCoverageLookup`). Returns `null` when no match
 * is found — older reports lack a `questionsCovered` array, and
 * the rare case where the model's two strings drift enough that
 * normalisation can't reconcile them. The card simply hides the
 * confidence / source pills in that case rather than picking the
 * wrong row.
 */
export function findCoverageMatch(
  item: PerQuestionAnalytics,
  lookup: ReadonlyMap<string, QuestionCovered> | null,
): QuestionCovered | null {
  if (lookup === null) return null;
  return lookup.get(normaliseQuestionKey(item.question_text)) ?? null;
}

/**
 * Mirror of `buildCoverageLookup` for `per_question_analytics`.
 * Used by the merged "Questions covered & Analytics" tab to walk
 * `questionsCovered` as the primary axis and pull the paired
 * analytics row for each entry. First-emitter wins on the rare
 * duplicate-key case, matching the coverage helper's contract.
 *
 * Returns `null` when the input is empty / undefined so the
 * caller can short-circuit the pairing loop.
 */
export function buildAnalyticsLookup(
  items: ReadonlyArray<PerQuestionAnalytics> | undefined,
): ReadonlyMap<string, PerQuestionAnalytics> | null {
  if (!items || items.length === 0) return null;
  const map = new Map<string, PerQuestionAnalytics>();
  for (const item of items) {
    const key = normaliseQuestionKey(item.question_text);
    if (!map.has(key)) map.set(key, item);
  }
  return map;
}

/**
 * Resolve the `PerQuestionAnalytics` entry paired with a given
 * `QuestionCovered` row. Symmetric counterpart of
 * `findCoverageMatch` — used by the merged-list builder so each
 * coverage row can pull in its STAR badges, metrics, and Rebuild
 * affordance from the analytics array. `null` for coverage rows
 * the analytics array doesn't carry (legacy report, post-launch
 * "LLM dropped this row", string drift) — the row renders in
 * coverage-only mode (pills + evidence quote, no STAR / metrics).
 */
export function findAnalyticsMatch(
  coverage: QuestionCovered,
  lookup: ReadonlyMap<string, PerQuestionAnalytics> | null,
): PerQuestionAnalytics | null {
  if (lookup === null) return null;
  return lookup.get(normaliseQuestionKey(coverage.question)) ?? null;
}

/**
 * Re-export the question-key normaliser so the merged-list
 * builder can mark analytics entries as "consumed" by their
 * normalised key when scanning for orphans. Kept internal-feeling
 * by lowercase naming; the merged-tab subtree is the only intended
 * caller outside this module.
 */
export function questionKey(text: string): string {
  return normaliseQuestionKey(text);
}

/* ────────────────────────────────────────────────────────────── */
/* Tab-mount property derivation                                  */
/* ────────────────────────────────────────────────────────────── */

/**
 * Pre-compute the booleans the `session_analytics_tab_viewed`
 * event ships so the mount effect stays a one-liner. Pure: no
 * window access here.
 */
export function deriveTabMountProperties(
  items: ReadonlyArray<PerQuestionAnalytics>,
): {
  question_count: number;
  has_profile_leverage_suggestions: boolean;
  has_weak_star_signals: boolean;
} {
  return {
    question_count: items.length,
    has_profile_leverage_suggestions: items.some(
      (i) => i.profile_leverage.status === "available_unused",
    ),
    has_weak_star_signals: items.some((i) => hasWeakOrMissingStar(i)),
  };
}
